name: helm-updater

on:
  workflow_call:
    inputs:
      service_name:
        description: "Name of the microservice"
        required: true
        type: string
      image_tag:
        description: "New image tag to write into values.yaml"
        required: true
        type: string
      helm_values_path:
        description: "Path to values file inside hipstershop-helm-charts repo"
        required: true
        type: string
      target_branch:
        description: "Branch to check out and push the values update to (main or develop)"
        required: false
        type: string
        default: main
    secrets:
      HELM_CHARTS_TOKEN:
        description: "PAT with contents:write on hipstershop-helm-charts repo"
        required: true


jobs:

  update-helm-values:
    name: update helm values
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hipstershop-helm-charts
        uses: actions/checkout@v4
        with:
          repository: HipsterShopp/hipstershop-helm-charts
          token: ${{ secrets.HELM_CHARTS_TOKEN }}
          ref: ${{ inputs.target_branch }}

      - name: Update image repo and tag
        run: |
          FILE="${{ inputs.helm_values_path }}"
          SERVICE="${{ inputs.service_name }}"
          TAG="${{ inputs.image_tag }}"
          Docker_Registry="yampss/hipstershop-$SERVICE"

          if [ ! -f "$FILE" ]; then
            echo "ERROR: $FILE not found in hipstershop-helm-charts repo"
            exit 1
          fi

          echo "Before:"
          grep -E "$SERVICE|tag:" "$FILE" || true

           # Replace full image string
           sed -i "s|^\(\s*$SERVICE:\s*\)\".*\"|\1\"$Docker_Registry:$TAG\"|" "$FILE"

          echo "After:"
          grep -E "$SERVICE|tag:" "$FILE" || true

      - name: Commit and push
        run: |
          git config user.name  "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "${{ inputs.helm_values_path }}"
          git diff --cached --quiet && echo "No changes — tag already up to date" && exit 0

          git commit -m "chore(${{ inputs.service_name }}): update image tag to ${{ inputs.image_tag }}"
          git push origin ${{ inputs.target_branch }}
